
version: '3'
services:
        redis:
                container_name: redis
                image: "redis:alpine"
                restart: always
                ports:
                        - 6379:6379
        postgres:
                image: postgres
                restart: on-failure
                environment:
                - POSTGRES_USER=postgresdocker
                - POSTGRES_PASSWORD=1234567890
                - PGDATA=/var/lib/postgresql/data/pgdata
                - POSTGRES_DB=postgres
                volumes:
                - ./postgres_data:/var/lib/postgresql
                ports:
                - 5432:5432